version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo  
    command: mongo --host mongo --eval  "db.getSiblingDB("kickoff").createUser({user:'kickoff', pwd:'kickoff', roles:['readWrite', 'dbAdmin']});"

  api:
    image: api:latest
    ports:
      - "7000:7000"

  comicbook:
    image: comicbook:latest
    ports:
      - "7001:7001"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=kickoff

  person:
    image: person:latest
    ports:
      - "7002:7002"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=kickoff      
