version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  comicbook:
    image: comicbook
    ports:
      - "7001:7001"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=kickoff