version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo  
    command: mongo --host mongo --eval  "db.getSiblingDB("kickoff").createUser({user:'kickoff', pwd:'kickoff', roles:['readWrite', 'dbAdmin']});"

  api:
    image: api:latest
    ports:
      - "7000:7000"
    environment:
      - COMICBOOK_URL=http://comicbook:7001
      - PERSON_URL=http://person:7002
      - API_PORT=7000
      - ZIPKIN_URL=http://zipkin:9411
      - ZIPKIN_PROBABILITY=1
      - ZIPKIN_ENABLED=true

  comicbook:
    image: comicbook:latest
    depends_on: 
      - kafka
      - zookeeper
    ports:
      - "7001:7001"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=kickoff
      - KAFKA_URL=kafka:9092
      - PERSON_URL=http://person:7002
      - COMICBOOK_PORT=7001
      - ZIPKIN_URL=http://zipkin:9411
      - ZIPKIN_PROBABILITY=1
      - ZIPKIN_ENABLED=true

  person:
    image: person.slim:latest
    depends_on: 
      - kafka
      - zookeeper
    ports:
      - "7002:7002"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=kickoff
      - KAFKA_URL=kafka:9092
      - PERSON_PORT=7002
      - ZIPKIN_URL=http://zipkin:9411
      - ZIPKIN_PROBABILITY=1
      - ZIPKIN_ENABLED=true

  zookeeper:
    image: wurstmeister/zookeeper
 
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
    volumes:
      - /tmp/kafka-comicbook-logs:/var/lib/kafka

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"