---
micronaut:
  application:
    name: api
  server:
    port: 7000
  http:
    services:
      comicbook:
        urls:
          - ${COMICBOOK_URL:http://localhost:7001/}
      person:
        urls:
          - ${PERSON_URL:http://localhost:7002/}
