---
micronaut:
  application:
    name: comicbook
  server:
    port: 7001
  http:
    services:
      person:
        urls:
          - ${PERSON_URL:http://localhost:7002/}
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:kickoff}"
---
kickoff:
  databaseName: ${MONGO_DATABASE:kickoff}
---
kafka:
  bootstrap:
    servers:
      - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}