---
micronaut:
  application:
    name: comicbook
  server:
    port: 7001
  http:
    services:
      person:
        urls:
          - http://localhost:7002/
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:kickoff}"
---
kickoff:
  databaseName: ${MONGO_DATABASE:kickoff}
---
kafka:
  bootstrap:
    servers: localhost:9092