---
micronaut:
  application:
    name: person
  server:
    port: ${PERSON_PORT:7002}

---
mongodb:
  uri: "${MONGO_URI:`mongodb://localhost:27017`}/${MONGO_DATABASE:kickoff}"
---
kickoff:
  databaseName: ${MONGO_DATABASE:kickoff}
---
kafka:
  bootstrap:
    servers:
      - ${KAFKA_URL:`localhost:9092`}
---
tracing:
  zipkin:
    http:
      url: ${ZIPKIN_URL:`http://localhost:9411`}
      follow-redirects: true
    enabled: ${ZIPKIN_ENABLED:true}
    sampler:
      probability: ${ZIPKIN_PROBABILITY:1}
