---
micronaut:
  application:
    name: person
  server:
    port: 7002

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:kickoff}"
---
kickoff:
  databaseName: ${MONGO_DATABASE:kickoff}